// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Get daily prayer times for the year
    ///
    /// - Remark: HTTP `GET /year/days/{year}.json`.
    /// - Remark: Generated from `#/paths//year/days/{year}.json/get(getYearPrayerTimesDays)`.
    func getYearPrayerTimesDays(_ input: Operations.GetYearPrayerTimesDays.Input) async throws -> Operations.GetYearPrayerTimesDays.Output
    /// Get weekly prayer times for the year
    ///
    /// - Remark: HTTP `GET /year/weeks/{year}.json`.
    /// - Remark: Generated from `#/paths//year/weeks/{year}.json/get(getYearPrayerTimesWeeks)`.
    func getYearPrayerTimesWeeks(_ input: Operations.GetYearPrayerTimesWeeks.Input) async throws -> Operations.GetYearPrayerTimesWeeks.Output
    /// Get SHA1 hash for the year
    ///
    /// - Remark: HTTP `GET /sha1/{year}.json`.
    /// - Remark: Generated from `#/paths//sha1/{year}.json/get(getYearPrayerTimesSha1)`.
    func getYearPrayerTimesSha1(_ input: Operations.GetYearPrayerTimesSha1.Input) async throws -> Operations.GetYearPrayerTimesSha1.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Get daily prayer times for the year
    ///
    /// - Remark: HTTP `GET /year/days/{year}.json`.
    /// - Remark: Generated from `#/paths//year/days/{year}.json/get(getYearPrayerTimesDays)`.
    public func getYearPrayerTimesDays(
        path: Operations.GetYearPrayerTimesDays.Input.Path,
        headers: Operations.GetYearPrayerTimesDays.Input.Headers = .init()
    ) async throws -> Operations.GetYearPrayerTimesDays.Output {
        try await getYearPrayerTimesDays(Operations.GetYearPrayerTimesDays.Input(
            path: path,
            headers: headers
        ))
    }
    /// Get weekly prayer times for the year
    ///
    /// - Remark: HTTP `GET /year/weeks/{year}.json`.
    /// - Remark: Generated from `#/paths//year/weeks/{year}.json/get(getYearPrayerTimesWeeks)`.
    public func getYearPrayerTimesWeeks(
        path: Operations.GetYearPrayerTimesWeeks.Input.Path,
        headers: Operations.GetYearPrayerTimesWeeks.Input.Headers = .init()
    ) async throws -> Operations.GetYearPrayerTimesWeeks.Output {
        try await getYearPrayerTimesWeeks(Operations.GetYearPrayerTimesWeeks.Input(
            path: path,
            headers: headers
        ))
    }
    /// Get SHA1 hash for the year
    ///
    /// - Remark: HTTP `GET /sha1/{year}.json`.
    /// - Remark: Generated from `#/paths//sha1/{year}.json/get(getYearPrayerTimesSha1)`.
    public func getYearPrayerTimesSha1(
        path: Operations.GetYearPrayerTimesSha1.Input.Path,
        headers: Operations.GetYearPrayerTimesSha1.Input.Headers = .init()
    ) async throws -> Operations.GetYearPrayerTimesSha1.Output {
        try await getYearPrayerTimesSha1(Operations.GetYearPrayerTimesSha1.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    /// Prayer Times service for Ibad Al-Rahman
    public enum Server1 {
        /// Prayer Times service for Ibad Al-Rahman
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://ibad-al-rahman.github.io/prayer-times/v1",
                variables: []
            )
        }
    }
    /// Prayer Times service for Ibad Al-Rahman
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://ibad-al-rahman.github.io/prayer-times/v1",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/YearPrayerTimesDays`.
        public struct YearPrayerTimesDays: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/YearPrayerTimesDays/year`.
            public var year: [Components.Schemas.Day]
            /// - Remark: Generated from `#/components/schemas/YearPrayerTimesDays/sha1`.
            public var sha1: Swift.String
            /// Creates a new `YearPrayerTimesDays`.
            ///
            /// - Parameters:
            ///   - year:
            ///   - sha1:
            public init(
                year: [Components.Schemas.Day],
                sha1: Swift.String
            ) {
                self.year = year
                self.sha1 = sha1
            }
            public enum CodingKeys: String, CodingKey {
                case year
                case sha1
            }
        }
        /// - Remark: Generated from `#/components/schemas/YearPrayerTimesWeeks`.
        public struct YearPrayerTimesWeeks: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/YearPrayerTimesWeeks/weeks`.
            public var weeks: [Components.Schemas.Week]
            /// - Remark: Generated from `#/components/schemas/YearPrayerTimesWeeks/sha1`.
            public var sha1: Swift.String
            /// Creates a new `YearPrayerTimesWeeks`.
            ///
            /// - Parameters:
            ///   - weeks:
            ///   - sha1:
            public init(
                weeks: [Components.Schemas.Week],
                sha1: Swift.String
            ) {
                self.weeks = weeks
                self.sha1 = sha1
            }
            public enum CodingKeys: String, CodingKey {
                case weeks
                case sha1
            }
        }
        /// - Remark: Generated from `#/components/schemas/Week`.
        public struct Week: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Week/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Week/mon`.
            public var mon: Components.Schemas.WeekDay?
            /// - Remark: Generated from `#/components/schemas/Week/tue`.
            public var tue: Components.Schemas.WeekDay?
            /// - Remark: Generated from `#/components/schemas/Week/wed`.
            public var wed: Components.Schemas.WeekDay?
            /// - Remark: Generated from `#/components/schemas/Week/thu`.
            public var thu: Components.Schemas.WeekDay?
            /// - Remark: Generated from `#/components/schemas/Week/fri`.
            public var fri: Components.Schemas.WeekDay?
            /// - Remark: Generated from `#/components/schemas/Week/sat`.
            public var sat: Components.Schemas.WeekDay?
            /// - Remark: Generated from `#/components/schemas/Week/sun`.
            public var sun: Components.Schemas.WeekDay?
            /// - Remark: Generated from `#/components/schemas/Week/hadith`.
            public var hadith: Components.Schemas.Hadith?
            /// Creates a new `Week`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - mon:
            ///   - tue:
            ///   - wed:
            ///   - thu:
            ///   - fri:
            ///   - sat:
            ///   - sun:
            ///   - hadith:
            public init(
                id: Swift.Int,
                mon: Components.Schemas.WeekDay? = nil,
                tue: Components.Schemas.WeekDay? = nil,
                wed: Components.Schemas.WeekDay? = nil,
                thu: Components.Schemas.WeekDay? = nil,
                fri: Components.Schemas.WeekDay? = nil,
                sat: Components.Schemas.WeekDay? = nil,
                sun: Components.Schemas.WeekDay? = nil,
                hadith: Components.Schemas.Hadith? = nil
            ) {
                self.id = id
                self.mon = mon
                self.tue = tue
                self.wed = wed
                self.thu = thu
                self.fri = fri
                self.sat = sat
                self.sun = sun
                self.hadith = hadith
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case mon
                case tue
                case wed
                case thu
                case fri
                case sat
                case sun
                case hadith
            }
        }
        /// - Remark: Generated from `#/components/schemas/WeekDay`.
        public struct WeekDay: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/WeekDay/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/WeekDay/gregorian`.
            public var gregorian: Swift.String
            /// - Remark: Generated from `#/components/schemas/WeekDay/hijri`.
            public var hijri: Swift.String
            /// - Remark: Generated from `#/components/schemas/WeekDay/prayerTimes`.
            public var prayerTimes: Components.Schemas.PrayerTimes?
            /// - Remark: Generated from `#/components/schemas/WeekDay/event`.
            public var event: Components.Schemas.Event?
            /// Creates a new `WeekDay`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - gregorian:
            ///   - hijri:
            ///   - prayerTimes:
            ///   - event:
            public init(
                id: Swift.Int,
                gregorian: Swift.String,
                hijri: Swift.String,
                prayerTimes: Components.Schemas.PrayerTimes? = nil,
                event: Components.Schemas.Event? = nil
            ) {
                self.id = id
                self.gregorian = gregorian
                self.hijri = hijri
                self.prayerTimes = prayerTimes
                self.event = event
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case gregorian
                case hijri
                case prayerTimes
                case event
            }
        }
        /// - Remark: Generated from `#/components/schemas/Day`.
        public struct Day: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Day/id`.
            public var id: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Day/weekId`.
            public var weekId: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Day/gregorian`.
            public var gregorian: Swift.String
            /// - Remark: Generated from `#/components/schemas/Day/hijri`.
            public var hijri: Swift.String
            /// - Remark: Generated from `#/components/schemas/Day/prayerTimes`.
            public var prayerTimes: Components.Schemas.PrayerTimes?
            /// - Remark: Generated from `#/components/schemas/Day/event`.
            public var event: Components.Schemas.Event?
            /// Creates a new `Day`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - weekId:
            ///   - gregorian:
            ///   - hijri:
            ///   - prayerTimes:
            ///   - event:
            public init(
                id: Swift.Int,
                weekId: Swift.Int,
                gregorian: Swift.String,
                hijri: Swift.String,
                prayerTimes: Components.Schemas.PrayerTimes? = nil,
                event: Components.Schemas.Event? = nil
            ) {
                self.id = id
                self.weekId = weekId
                self.gregorian = gregorian
                self.hijri = hijri
                self.prayerTimes = prayerTimes
                self.event = event
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case weekId
                case gregorian
                case hijri
                case prayerTimes
                case event
            }
        }
        /// - Remark: Generated from `#/components/schemas/PrayerTimes`.
        public struct PrayerTimes: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/PrayerTimes/fajr`.
            public var fajr: Swift.String
            /// - Remark: Generated from `#/components/schemas/PrayerTimes/sunrise`.
            public var sunrise: Swift.String
            /// - Remark: Generated from `#/components/schemas/PrayerTimes/dhuhr`.
            public var dhuhr: Swift.String
            /// - Remark: Generated from `#/components/schemas/PrayerTimes/asr`.
            public var asr: Swift.String
            /// - Remark: Generated from `#/components/schemas/PrayerTimes/maghrib`.
            public var maghrib: Swift.String
            /// - Remark: Generated from `#/components/schemas/PrayerTimes/ishaa`.
            public var ishaa: Swift.String
            /// Creates a new `PrayerTimes`.
            ///
            /// - Parameters:
            ///   - fajr:
            ///   - sunrise:
            ///   - dhuhr:
            ///   - asr:
            ///   - maghrib:
            ///   - ishaa:
            public init(
                fajr: Swift.String,
                sunrise: Swift.String,
                dhuhr: Swift.String,
                asr: Swift.String,
                maghrib: Swift.String,
                ishaa: Swift.String
            ) {
                self.fajr = fajr
                self.sunrise = sunrise
                self.dhuhr = dhuhr
                self.asr = asr
                self.maghrib = maghrib
                self.ishaa = ishaa
            }
            public enum CodingKeys: String, CodingKey {
                case fajr
                case sunrise
                case dhuhr
                case asr
                case maghrib
                case ishaa
            }
        }
        /// - Remark: Generated from `#/components/schemas/Event`.
        public struct Event: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Event/en`.
            public var en: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Event/ar`.
            public var ar: Swift.String
            /// Creates a new `Event`.
            ///
            /// - Parameters:
            ///   - en:
            ///   - ar:
            public init(
                en: Swift.String? = nil,
                ar: Swift.String
            ) {
                self.en = en
                self.ar = ar
            }
            public enum CodingKeys: String, CodingKey {
                case en
                case ar
            }
        }
        /// - Remark: Generated from `#/components/schemas/Hadith`.
        public struct Hadith: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Hadith/hadith`.
            public var hadith: Swift.String
            /// - Remark: Generated from `#/components/schemas/Hadith/note`.
            public var note: Swift.String?
            /// Creates a new `Hadith`.
            ///
            /// - Parameters:
            ///   - hadith:
            ///   - note:
            public init(
                hadith: Swift.String,
                note: Swift.String? = nil
            ) {
                self.hadith = hadith
                self.note = note
            }
            public enum CodingKeys: String, CodingKey {
                case hadith
                case note
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// Get daily prayer times for the year
    ///
    /// - Remark: HTTP `GET /year/days/{year}.json`.
    /// - Remark: Generated from `#/paths//year/days/{year}.json/get(getYearPrayerTimesDays)`.
    public enum GetYearPrayerTimesDays {
        public static let id: Swift.String = "getYearPrayerTimesDays"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/year/days/{year}.json/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/year/days/{year}.json/GET/path/year`.
                public var year: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - year:
                public init(year: Swift.String) {
                    self.year = year
                }
            }
            public var path: Operations.GetYearPrayerTimesDays.Input.Path
            /// - Remark: Generated from `#/paths/year/days/{year}.json/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetYearPrayerTimesDays.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetYearPrayerTimesDays.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.GetYearPrayerTimesDays.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.GetYearPrayerTimesDays.Input.Path,
                headers: Operations.GetYearPrayerTimesDays.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/year/days/{year}.json/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/year/days/{year}.json/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.YearPrayerTimesDays)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.YearPrayerTimesDays {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.GetYearPrayerTimesDays.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.GetYearPrayerTimesDays.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful response
            ///
            /// - Remark: Generated from `#/paths//year/days/{year}.json/get(getYearPrayerTimesDays)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.GetYearPrayerTimesDays.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.GetYearPrayerTimesDays.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Get weekly prayer times for the year
    ///
    /// - Remark: HTTP `GET /year/weeks/{year}.json`.
    /// - Remark: Generated from `#/paths//year/weeks/{year}.json/get(getYearPrayerTimesWeeks)`.
    public enum GetYearPrayerTimesWeeks {
        public static let id: Swift.String = "getYearPrayerTimesWeeks"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/year/weeks/{year}.json/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/year/weeks/{year}.json/GET/path/year`.
                public var year: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - year:
                public init(year: Swift.String) {
                    self.year = year
                }
            }
            public var path: Operations.GetYearPrayerTimesWeeks.Input.Path
            /// - Remark: Generated from `#/paths/year/weeks/{year}.json/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetYearPrayerTimesWeeks.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetYearPrayerTimesWeeks.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.GetYearPrayerTimesWeeks.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.GetYearPrayerTimesWeeks.Input.Path,
                headers: Operations.GetYearPrayerTimesWeeks.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/year/weeks/{year}.json/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/year/weeks/{year}.json/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.YearPrayerTimesWeeks)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.YearPrayerTimesWeeks {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.GetYearPrayerTimesWeeks.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.GetYearPrayerTimesWeeks.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful response
            ///
            /// - Remark: Generated from `#/paths//year/weeks/{year}.json/get(getYearPrayerTimesWeeks)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.GetYearPrayerTimesWeeks.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.GetYearPrayerTimesWeeks.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Get SHA1 hash for the year
    ///
    /// - Remark: HTTP `GET /sha1/{year}.json`.
    /// - Remark: Generated from `#/paths//sha1/{year}.json/get(getYearPrayerTimesSha1)`.
    public enum GetYearPrayerTimesSha1 {
        public static let id: Swift.String = "getYearPrayerTimesSha1"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/sha1/{year}.json/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/sha1/{year}.json/GET/path/year`.
                public var year: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - year:
                public init(year: Swift.String) {
                    self.year = year
                }
            }
            public var path: Operations.GetYearPrayerTimesSha1.Input.Path
            /// - Remark: Generated from `#/paths/sha1/{year}.json/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetYearPrayerTimesSha1.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetYearPrayerTimesSha1.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.GetYearPrayerTimesSha1.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.GetYearPrayerTimesSha1.Input.Path,
                headers: Operations.GetYearPrayerTimesSha1.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/sha1/{year}.json/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/sha1/{year}.json/GET/responses/200/content/json`.
                    public struct JsonPayload: Codable, Hashable, Sendable {
                        /// - Remark: Generated from `#/paths/sha1/{year}.json/GET/responses/200/content/json/sha1`.
                        public var sha1: Swift.String
                        /// Creates a new `JsonPayload`.
                        ///
                        /// - Parameters:
                        ///   - sha1:
                        public init(sha1: Swift.String) {
                            self.sha1 = sha1
                        }
                        public enum CodingKeys: String, CodingKey {
                            case sha1
                        }
                    }
                    /// - Remark: Generated from `#/paths/sha1/{year}.json/GET/responses/200/content/application\/json`.
                    case json(Operations.GetYearPrayerTimesSha1.Output.Ok.Body.JsonPayload)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Operations.GetYearPrayerTimesSha1.Output.Ok.Body.JsonPayload {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.GetYearPrayerTimesSha1.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.GetYearPrayerTimesSha1.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful response
            ///
            /// - Remark: Generated from `#/paths//sha1/{year}.json/get(getYearPrayerTimesSha1)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.GetYearPrayerTimesSha1.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.GetYearPrayerTimesSha1.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
