name: ci

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ios-ci:
    uses: ibad-al-rahman/.github/.github/workflows/ios-ci.yml@master
    with:
      xcode_project: PublicSector.xcodeproj
      xcode_scheme: PublicSector
      default_branch: master
